# Generated by Django 4.2.3 on 2023-08-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
